version: 0.2

phases:
  pre_build:
    commands:
      - echo Node version
      - node --version
      - echo NPM version
      - npm --version
      - echo installing Vuepress
      - npm install -g @vuepress/cli
      - npm install -g vuepress
      - vuepress --version
      - npm install -D @vuepress/theme-blog
      - npm install -D @vuepress/plugin-blog
  build:
    commands:
      - echo Build started on `date`
      - vuepress build
  post_build:
    commands:
      - echo Build completed on `date`