version: 0.2

phases:
  pre_build:
    commands:
      - node --version
      - npm --version
      - echo installing Vuepress
      - npm install -g vuepress --unsafe-perm
      - vuepress --version
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - vuepress build
  post_build:
    commands:
      - echo Build completed on `date`