version: 0.2

phases:
  pre_build:
    commands:
      - echo installing Vuepress
      - npm install -g vuepress
  build:
    commands:
      - echo Build started on `date`
      - vuepress build
  post_build:
    commands:
      - echo Build completed on `date`